### ISSUE TITLE
Create gh-pages branch and move the code to there

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/miami-budget#2]
If you create a `gh-pages` branch and move the code from `master` to there, you can take care of jekyll functionality. That way the URL can be http://codeformiami.org/miami-budget

**Comment by ErnieAtLYD** [comment]
https://help.github.com/articles/using-jekyll-with-pages/

**Comment by maurop123** [comment]
Another idea would be to make a codeformiami subdomain like, miamibudget.codeformiami.com, at which point I'd like to host that on my AWS server in order to put it on a Meteor.js stack. That way this has an easy avenue of becoming an app. Additionally, it can have features like auto-deploy and such.

What do you think @ErnieAtLYD ?

**Comment by ErnieAtLYD** [comment]
so codeformiami.org is already DNS mapped to the github `gh-pages` branch. So any project that gets will be mapped to codeformiami.org - I actually have NO idea how subdomains work within the context of github, maybe @CristinaSolana or @CyberStrike knows?

I don't think meteor.js and github pages play nice together. But if there is functionality that will be added that will supercharge the budget app where meteor is necessary it may make sense to host the code somewhere else with a new domain (due to the previously mentioned mapping issues.)

**Comment by maurop123** [comment]
http://miamigraph.com exists and takes care of this.
